### ISSUE TITLE
Question about binary stream functions

### ISSUE THREAD

**Issue by ScarletRedMan** [Podrum/Podrum#8]
https://github.com/Podrum/Podrum/blob/a2824ed303c8aa5879477f78fc86487d991dcf89/cbinarystream/binary_stream.c#L39

What is difference betwen `get_SomeType_le()` and `get_SomeType_be()`?

**Comment by ZaZiDev** [comment]
le = little endian 
be = big endian
it is a byte order

**Comment by ScarletRedMan** [comment]
Thanks
